version: '3'
services:
  ionic:
    container_name: ionic
    image: fabiojanio/ionic:3.20.0
    volumes:
      - /Users/fabio-janio/Projetos/desenvolvimento-web/gTarefas/:/app
    restart: on-failure
    ports:
      - 8100:8100
      - 35729:35729
      - 53703:53703